config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :oenologists
  resources :wine_strains
  resources :strains
  resources :wines

  root to: "wines#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/oenologist.rb
class Oenologist < ApplicationRecord
    has_many:wines 
end

app/controllers/oenologists_controller.rb
class OenologistsController < ApplicationController
  before_action :set_oenologist, only: %i[ show edit update destroy ]

  # GET /oenologists or /oenologists.json
  def index
    @oenologists = Oenologist.all
  end

  # GET /oenologists/1 or /oenologists/1.json
  def show
  end

  # GET /oenologists/new
  def new
    @oenologist = Oenologist.new
  end

  # GET /oenologists/1/edit
  def edit
  end

  # POST /oenologists or /oenologists.json
  def create
    @oenologist = Oenologist.new(oenologist_params)

    respond_to do |format|
      if @oenologist.save
        format.html { redirect_to @oenologist, notice: "Oenologist was successfully created." }
        format.json { render :show, status: :created, location: @oenologist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @oenologist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /oenologists/1 or /oenologists/1.json
  def update
    respond_to do |format|
      if @oenologist.update(oenologist_params)
        format.html { redirect_to @oenologist, notice: "Oenologist was successfully updated." }
        format.json { render :show, status: :ok, location: @oenologist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @oenologist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /oenologists/1 or /oenologists/1.json
  def destroy
    @oenologist.destroy
    respond_to do |format|
      format.html { redirect_to oenologists_url, notice: "Oenologist was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_oenologist
      @oenologist = Oenologist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def oenologist_params
      params.require(:oenologist).permit(:name, :age, :nationality)
    end
end

app/helpers/oenologists_helper.rb
module OenologistsHelper
end

app/views/oenologists/_form.html.erb
<%= form_with(model: oenologist, local: true) do |form| %>
  <% if oenologist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(oenologist.errors.count, "error") %> prohibited this oenologist from being saved:</h2>

      <ul>
      <% oenologist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :nationality %>
    <%= form.text_field :nationality %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/oenologists/edit.html.erb
<h1>Editing Oenologist</h1>

<%= render 'form', oenologist: @oenologist %>

<%= link_to 'Show', @oenologist %> |
<%= link_to 'Back', oenologists_path %>

app/views/oenologists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Oenologists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Nationality</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @oenologists.each do |oenologist| %>
      <tr>
        <td><%= oenologist.name %></td>
        <td><%= oenologist.age %></td>
        <td><%= oenologist.nationality %></td>
        <td><%= link_to 'Show', oenologist %></td>
        <td><%= link_to 'Edit', edit_oenologist_path(oenologist) %></td>
        <td><%= link_to 'Destroy', oenologist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Oenologist', new_oenologist_path %>

app/views/oenologists/new.html.erb
<h1>New Oenologist</h1>

<%= render 'form', oenologist: @oenologist %>

<%= link_to 'Back', oenologists_path %>

app/views/oenologists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @oenologist.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @oenologist.age %>
</p>

<p>
  <strong>Nationality:</strong>
  <%= @oenologist.nationality %>
</p>

<%= link_to 'Edit', edit_oenologist_path(@oenologist) %> |
<%= link_to 'Back', oenologists_path %>