config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :oenologists
  resources :wine_strains
  resources :strains
  resources :wines

  root to: "wines#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/wine_strain.rb
class WineStrain < ApplicationRecord
  belongs_to :wine
  belongs_to :strain
end

app/controllers/wine_strains_controller.rb
class WineStrainsController < ApplicationController
  before_action :set_wine_strain, only: %i[ show edit update destroy ]


  # GET /wine_strains or /wine_strains.json
  def index
    @wine_strains = WineStrain.all
  end

  # GET /wine_strains/1 or /wine_strains/1.json
  def show
  end

  # GET /wine_strains/new
  def new
    @wine_strain = WineStrain.new
  end

  # GET /wine_strains/1/edit
  def edit
  end

  # POST /wine_strains or /wine_strains.json
  def create
    @wine_strain = WineStrain.new(wine_strain_params)

    respond_to do |format|
      if @wine_strain.save
        format.html { redirect_to @wine_strain, notice: "Wine strain was successfully created." }
        format.json { render :show, status: :created, location: @wine_strain }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wine_strain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wine_strains/1 or /wine_strains/1.json
  def update
    respond_to do |format|
      if @wine_strain.update(wine_strain_params)
        format.html { redirect_to @wine_strain, notice: "Wine strain was successfully updated." }
        format.json { render :show, status: :ok, location: @wine_strain }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wine_strain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wine_strains/1 or /wine_strains/1.json
  def destroy
    @wine_strain.destroy
    respond_to do |format|
      format.html { redirect_to wine_strains_url, notice: "Wine strain was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wine_strain
      @wine_strain = WineStrain.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wine_strain_params
      params.require(:wine_strain).permit(:wine_id, :strain_id, :percentage)
    end
end

app/helpers/wine_strains_helper.rb
module WineStrainsHelper
end

app/views/wine_strains/_form.html.erb
<%= form_with(model: wine_strain, local: true) do |form| %>
  <% if wine_strain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wine_strain.errors.count, "error") %> prohibited this wine_strain from being saved:</h2>

      <ul>
      <% wine_strain.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :wine_id %>
    <%= form.text_field :wine_id %>
  </div>

  <div class="field">
    <%= form.label :strain_id %>
    <%= form.text_field :strain_id %>
  </div>

  <div class="field">
    <%= form.label :percentage %>
    <%= form.number_field :percentage %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wine_strains/edit.html.erb
<h1>Editing Wine Strain</h1>

<%= render 'form', wine_strain: @wine_strain %>

<%= link_to 'Show', @wine_strain %> |
<%= link_to 'Back', wine_strains_path %>

app/views/wine_strains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wine Strains</h1>

<table>
  <thead>
    <tr>
      <th>Wine</th>
      <th>Strain</th>
      <th>Percentage</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wine_strains.each do |wine_strain| %>
      <tr>
        <td><%= wine_strain.wine %></td>
        <td><%= wine_strain.strain %></td>
        <td><%= wine_strain.percentage %></td>
        <td><%= link_to 'Show', wine_strain %></td>
        <td><%= link_to 'Edit', edit_wine_strain_path(wine_strain) %></td>
        <td><%= link_to 'Destroy', wine_strain, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wine Strain', new_wine_strain_path %>

app/views/wine_strains/new.html.erb
<h1>New Wine Strain</h1>

<%= render 'form', wine_strain: @wine_strain %>

<%= link_to 'Back', wine_strains_path %>

app/views/wine_strains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Wine:</strong>
  <%= @wine_strain.wine %>
</p>

<p>
  <strong>Strain:</strong>
  <%= @wine_strain.strain %>
</p>

<p>
  <strong>Percentage:</strong>
  <%= @wine_strain.percentage %>
</p>

<%= link_to 'Edit', edit_wine_strain_path(@wine_strain) %> |
<%= link_to 'Back', wine_strains_path %>