config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :oenologists
  resources :wine_strains
  resources :strains
  resources :wines

  root to: "wines#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/wine.rb
class Wine < ApplicationRecord
    has_many :wine_strains
    has_many :strains, through: :wine_strains

    has_and_belongs_to_many :oenologists

    def  addStrainPercent(percents)
        percents.each do |strain_id, percentage|
            if percentage != ""
               temp_strain = self.wine_strains.where(strain_id: strain_id.to_i).first
               temp_strain.percentage = percentage.to_i
               temp_strain.save
            end
        end 
    end

    def getPercentageByStrainId(strain_id)
        if self.wine_strains.where(strain_id: strain_id.to_i).first
            self.wine_strains.where(strain_id: strain_id.to_i).first.percentage
        end
    end
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :authorize_admin!, except: [:index]
  before_action :set_wine, only: %i[ show edit update destroy ]
  before_action :only_strains_availables, only:[:new, :edit]





  # GET /wines or /wines.json
  def index
    @wines = Wine.all
  end

  # GET /wines/1 or /wines/1.json
  def show
  end

  # GET /wines/new
  def new
    @wine = Wine.new
  end

  # GET /wines/1/edit
  def edit
    @oenologists = Oenologist.order(:age)
  end

  # POST /wines or /wines.json
  def create
    @wine = Wine.new(wine_params)

    respond_to do |format|
      if @wine.save
        @wine.addStrainPercent(params[:wine][:strains_percent])

        format.html { redirect_to @wine, notice: "Wine was successfully created." }
        format.json { render :show, status: :created, location: @wine }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wines/1 or /wines/1.json
  def update
    respond_to do |format|
      if @wine.update(wine_params)
        @wine.oenologists.destroy_all
        @wine.oenologists << Oenologist.where(id: params[:wine][:oenologists])
        @wine.addStrainPercent(params[:wine][:strains_percent])
        format.html { redirect_to @wine, notice: "Wine was successfully updated." }
        format.json { render :show, status: :ok, location: @wine }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wines/1 or /wines/1.json
  def destroy
    @wine.destroy
    respond_to do |format|
      format.html { redirect_to wines_url, notice: "Wine was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wine
      @wine = Wine.find(params[:id])
    end

    def only_strains_availables
      @strains_availables = Strain.where(available: true)
    end

    # Only allow a list of trusted parameters through.
    def wine_params
      params.require(:wine).permit(:name, :score, {strain_ids: []}, :strains_percent)
    end
  end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/wines/_form.html.erb
<%= form_with(model: wine, local: true) do |form| %>
  <% if wine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wine.errors.count, "error") %> prohibited this wine from being saved:</h2>

      <ul>
      <% wine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>



  <div class="field">
    <%= form.label :strains %>
    <%= form.collection_check_boxes(:strain_ids, @strains_availables, :id, :name) do |b| %>
       <%= b.label class:"label-checkbox" do  %>
         <%= b.check_box + b.text %>
         <%= text_field( "wine[strains_percent]", b.value, value: @wine.getPercentageByStrainId(b.value)) %>
         <br/>
       <% end  %>
    <% end  %>
  </div>

<% if @oenologists %>
  <div class="field">
    <%= form.label :score %>
    <%= form.number_field :score %>
  </div>

  <div class="field">
    <%= form.label :oenologists %>
    <%= form.collection_check_boxes(:oenologists, @oenologists, :id, :name) do |o| %>
    <%= o.label class:"label-checkbox" do %>
    <% if  @wine.oenologists.pluck(:id).include? (o.value) %>
       <%= o.check_box({checked: true}) + o.text %>
    <% else %>
       <%= o.check_box + o.text %>
    <% end %>
    <br/>
    <% end %>
    <% end %>
  </div>
  <% end %>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wines/edit.html.erb
<h1>Editing Wine</h1>

<%= render 'form', wine: @wine %>

<%= link_to 'Show', @wine %> |
<%= link_to 'Back', wines_path %>

app/views/wines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wines</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
       <th>Strains</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wines.each do |wine| %>
      <tr>
        <td><%= wine.name %></td>
        <td>
          <%= wine.strains.order(:name).map{|s| "#{s.name} (#{wine.getPercentageByStrainId(s.id)} % ) "}  %>
        </td>
        <td><%= wine.score %></td>
        <td><%= link_to 'Show', wine %></td>
        <td><%= link_to 'Edit', edit_wine_path(wine) %></td>
        <td><%= link_to 'Destroy', wine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wine', new_wine_path %>

app/views/wines/new.html.erb
<h1>New Wine</h1>

<%= render 'form', wine: @wine %>

<%= link_to 'Back', wines_path %>

app/views/wines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @wine.name %>
</p>

<p>
  <strong>Score:</strong>
  <%= @wine.score %>
</p>

<%= link_to 'Edit', edit_wine_path(@wine) %> |
<%= link_to 'Back', wines_path %>